- hosts: all
  become: false
  gather_facts: false

  vars_files:
    - vars/defaults.yml

  tasks:
    # - name: Ping the machine
    #   ping:
    
    - name: Configure repository
      become: true
      yum_repository:
        name: docker
        description: Docker repository
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgkey: https://download.docker.com/linux/centos/gpg

    # - name: Remove old content
    #   become: true
    #   yum:
    #     name: "{{ item }}"
    #     state: absent
    #   loop: ['docker-ce', 'python-virtualenv', 'gcc', 'python2-pip', 'python3-pip', 'epel-release']

    - name: Install EPEL
      package:
        name: epel-release
        state: present
      become: true
        
    - name: Install Docker and pip
      package:
        name: "{{ item }}"
      loop: ['docker-ce', 'python-pip']
      become: true

    - name: Start and enable the Docker daemon
      service: 
        name: docker
        state: started
        enabled: yes
      become: true
    
    - name: Install Docker module for Python
      pip:
        name: docker-py
      become: true

    - name: Login to Github Docker registry
      docker_login:
        registry_url: "{{ registry_url }}"
        username: "Bastien Pateyron"
        password: "{{ GITHUB_TOKEN }}"
      become: true
      changed_when: false

    - name: Pull Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
      become: true

    - name: Create and start containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        recreate: yes
        state: started
        ports:
          - "{{ default_container_application_port }}"
      with_sequence: count={{ create_containers }}
      become: true
      
    - name: Logout from docker registry
      docker_login:
        registry_url: "{{ registry_url }}"
        username: "Bastien Pateyron"
        password: "{{ GITHUB_TOKEN }}"
        state: absent
      become: true
      changed_when: false
    

