- hosts: all
  become: false
  gather_facts: false

  vars_files:
    - vars/defaults.yml

  tasks:

    - name: Install Docker
      include: "{{ playbook_dir }}/tasks/install-docker-centos.yml"

    - name: Deploy docker image
      include: "{{ playbook_dir }}/tasks/deploy-docker-image.yml"

# TODO: Add a healthcheck for the container
