---
- name: Login to Github Docker registry
  docker_login:
    registry_url: "{{ registry_url }}"
    username: "Bastien Pateyron"
    password: "{{ GITHUB_TOKEN }}"
  become: true
  changed_when: false

- name: Remove old containers
  docker_container:
    name: "{{ default_container_name }}{{ item }}"
    image: "{{ default_container_image }}"
    state: absent
    ports:
      - "{{ default_container_application_port }}"
  with_sequence: count={{ create_containers }}
  become: true

- name: Remove old image
  docker_image:
    state: absent
    name: "{{ default_container_image }}"
    tag: latest
  become: true

- name: Pull Docker image
  docker_image:
    name: "{{ default_container_image }}"
    source: pull
  become: true

- name: Create and start containers
  docker_container:
    name: "{{ default_container_name }}{{ item }}"
    image: "{{ default_container_image }}"
    recreate: true
    state: started
    ports:
      - "{{ default_container_application_port }}"
  with_sequence: count={{ create_containers }}
  become: true

- name: Logout from docker registry
  docker_login:
    registry_url: "{{ registry_url }}"
    username: "Bastien Pateyron"
    password: "{{ GITHUB_TOKEN }}"
    state: absent
  become: true
  changed_when: false
