image_name: portfolio
registry: ghcr.io/bastienpateyron
registry_url: "https://ghcr.io"

create_containers: 1
default_container_name: portfolio
default_container_image: "{{ registry }}/{{ image_name }}:latest"
default_container_command: sleep 1d
default_container_application_port: "80:80"

# ansible_ssh_private_key_file: "~/.ssh/id_rsa"
ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
# ansible_ssh_private_key_file: "${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}"
